### PR TITLE
Fix dynamic theme usage

### LINKED ISSUE #98: Example app crashes on start
The stack trace:
```
Process: com.alorma.compose.settings.example, PID: 16781
android.content.res.Resources$NotFoundException: Resource ID #0x1060028
 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
 	at android.content.res.Resources.getColor(Resources.java:961)
 	at androidx.compose.material3.ColorResourceHelper.getColor-WaAFU9c(DynamicTonalPalette.kt:186)
 	at androidx.compose.material3.DynamicTonalPaletteKt.dynamicTonalPalette(DynamicTonalPalette.kt:41)
 	at androidx.compose.material3.DynamicTonalPaletteKt.dynamicDarkColorScheme(DynamicTonalPalette.kt:155)
 	at com.alorma.compose.settings.example.ui.theme.ThemeKt.ComposeSettingsTheme(Theme.kt:20)
 	at com.alorma.compose.settings.example.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:41)
 	at com.alorma.compose.settings.example.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:28)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:404)
 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:250)
 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:249)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
```

Looks like something is wrong with resources

### PR DESCRIPTION
**Pull request by pelmenstar1**
Fixes #98

### CODE REVIEW

File: app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt [hunk 1]
```diff
@@ -12,13 +12,7 @@ import androidx.navigation.compose.NavHost
...
 import androidx.navigation.compose.rememberNavController
 import com.alorma.compose.settings.example.ui.Navigation
-import com.alorma.compose.settings.example.ui.screens.AppSettingsScreen
-import com.alorma.compose.settings.example.ui.screens.CheckboxesScreen
-import com.alorma.compose.settings.example.ui.screens.ListScreen
-import com.alorma.compose.settings.example.ui.screens.MenuLinksScreen
-import com.alorma.compose.settings.example.ui.screens.SlidersScreen
-import com.alorma.compose.settings.example.ui.screens.SwitchesScreen
-import com.alorma.compose.settings.example.ui.screens.TopLevelScreen
+import com.alorma.compose.settings.example.ui.screens.*
```
Comment (alorma) [inline app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt:15]: Could you revert the wildcard imports? I prefer to have a list of imports instead of generic import.

Btw. I should add a codeStyle to the project.

File: app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt [hunk 2]
```diff
@@ -34,7 +28,7 @@ class MainActivity : ComponentActivity() {
 
       val dynamicThemePreference = rememberPreferenceBooleanSettingState(
         key = "dynamicThemePreference",
-        defaultValue = true,
+        defaultValue = true
```
Comment (alorma) [inline app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt:31]: Keep the trailing comma

**Review by alorma — APPROVED** [review]
Cool! Thanks!

Could you address the comments please?

File: app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt (hunk 1 above)
Comment (pelmenstar1) [reply app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt]: Fixed

File: app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt (hunk 2 above)
Comment (pelmenstar1) [reply app/src/main/java/com/alorma/compose/settings/example/MainActivity.kt]: Fixed

**Comment by alorma** [comment]
Much appreciated!!!
